### ISSUE TITLE
Must be the wrong place to do so!

### ISSUE THREAD

**Issue by AhmadQadah** [stuisme/VineSharp#2]
Hello,

Couldn't find a way to contact you,

But I can't seem to find a way to "follow a specific userId" ? is this possible through Vine API? i can't seem to find a decent documentation regarding anything thats related to that.

**Comment by stuisme** [comment]
Potentially, you could rotate through the pages of a users timeline and filter out other users. Since the API is undocumented, there may or may not be a better way to do this. 

You can get a users timeline: VineClient.UserTimeline
https://github.com/stuisme/VineSharp/blob/master/VineSharp/VineClient.cs#L171

Unlikely, but you could try different urls like:

https://api.vineapp.com/users/906264212790190080/posts 
-or-
https://api.vineapp.com/posts?userId=xxx (or user=xxx)

(I have no clue if these work)
